# Generated by Django 5.2.1 on 2025-06-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
