# Generated by Django 5.2.1 on 2025-06-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_app', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
