# Generated by Django 5.2.4 on 2025-08-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_app', '0004_rename_createdat_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('engine compartment', 'Engine compartment'), ('interior', 'Interior'), ('chassis', 'Chassis'), ('transmission', 'Transmission')], default='transmission', max_length=20),
        ),
    ]
