# Generated by Django 5.2.4 on 2025-09-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_app', '0006_product_on_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('engine compartment', 'Engine compartment'), ('interior', 'Interior'), ('chassis', 'Chassis'), ('transmission', 'Transmission'), ('electronics', 'Electronics'), ('brake system', 'Brake system')], default='transmission', max_length=20),
        ),
    ]
