# Generated by Django 5.2.4 on 2025-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_app', '0009_order_shipping_address_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_phone',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
