# Generated by Django 5.2.4 on 2025-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_app', '0010_orderitem_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
