# Generated by Django 5.2.4 on 2025-10-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_app', '0011_remove_orderitem_customer_phone_order_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
